// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziqqhebtaiuwknhbmkrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppcXFoZWJ0YWl1d2tuaGJta3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjUxNjUsImV4cCI6MjA2MzY0MTE2NX0.BfEyhVqLcO7uyfTPczfurZfq_vopn__v6uEbQfzCnkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);